# Generated by Django 5.1.7 on 2025-04-14 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_historico'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ambientes',
            old_name='descricao_sig',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='ambientes',
            old_name='num_sala',
            new_name='sig',
        ),
        migrations.RemoveField(
            model_name='ambientes',
            name='num_sig',
        ),
        migrations.RemoveField(
            model_name='manutentores',
            name='ni',
        ),
        migrations.AddField(
            model_name='gestores',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gestores',
            name='is_superUser',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='manutentores',
            name='gestor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.gestores'),
        ),
        migrations.AddField(
            model_name='manutentores',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='manutentores',
            name='is_superUser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='responsaveis',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='responsaveis',
            name='is_superUser',
            field=models.BooleanField(default=False),
        ),
    ]
