# Generated by Django 5.1.7 on 2025-04-15 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_descricao_sig_ambientes_descricao_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manutentores',
            old_name='gestor_id',
            new_name='gestor',
        ),
    ]
