import os
import django

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'backend.settings')
django.setup()

import random
from api.models import Responsaveis, Gestores

nomes = [
    "CESAR AUGUSTO DA COSTA", "ANDERSON APARECIDO FELIX", "DOMINIQUE MISSIO DE FARIA",
    "ANGELO RAFAIM NETO", "JEANE LEMOS REAL", "JESSICA TEIGA CONDECELLI", 
    "VICTOR MAURÍCIO CONDECELLI SENA SILVA", "RODRIGO ALVES PINTO", "FABIO KURANAKA",
    "LEANDRO CESAR RECCHIA", "MARCUS VINICIUS BEGOSSI", "CELSO MARTINEZ",
    "ELIAS MORAES PRATES", "RICARDO BARBI", "EDUARDO DE CASTRO QUINTINO",
    "CARLOS ALBERTO SOUZA BARROSO", "MARCIA CRISTINA", "VICTOR SERRA BRAGA LEMOS",
    "SERGIO BORCATO", "KELLY CRISTINA NUNES SEGUNDO", "ROBSON LUIZ FRONZA",
    "ALEXANDRE DONISETE MEYER", "ISRAEL GOMES DA SILVA", "EDIANE GABRIELA RIBEIRO KURANAKA",
    "MICHEL MODESTO LÚCIO", "ODAIR ROPELLE", "ADRIANO LUIZ PEDRINI", "JOSE NEVES BEZERRA JUNIOR",
    "ULISSES BENATTI", "ALAN MOZZAQUATTRO", "FLORENCIA ISABEL VAZQUEZ FERNANDEZ",
    "THYAGO NERI FERREIRA", "JULIANA DEFENSOR DE SOUZA", "ALEX TOLEDO PIZA",
    "JEFERSON SPERLICK", "EDUARDO PEREIRA MORAES", "FERNANDO MIGUEL ALEGRETTI",
    "ANTONIO GUEDES NETO", "LINDOMAR JOSE BATISTAO", "CLEBER BALBINO DA COSTA",
    "ARMANDO LUIS DONO", "DALTON GONÇALVES", "EDUARDO DOS SANTOS PEDROSA",
    "LUIZ DE OLIVEIRA SANTOS", "ROBERTO GIANI PATTARO JUNIOR", "ANTONIO CARLOS THEZOLIM",
    "LUIS FERNANDO MARTINS", "HUGO SAKAI IDAGAWA", "RICARDO FAVARO", "RENATO PILAN",
    "LUCAS ANDRADE FIAIS DE CARVALHO", "MARCOS HENRIQUE DELLA COLLETA", "MARCELO AFONSO",
    "WENISON SANTOS DE NOVAIS", "GERSON DE CARVALHO ANDRADE", "ROBERTTEIN DE OLIVEIRA SILVA",
    "MARCELO LUIZ NUNES", "CARLOS ROBERTO COLDIBELI MENDONÇA", "DEMETRIO GONÇALVES DA SILVA",
    "EDSON ARAÚJO", "ROGÉRIO DAS NEVES PEREIRA", "LUIS CARLOS DE SOUZA",
    "LUIZ CARLOS DE OLIVEIRA FRANCISCO", "JOÃO MARCELO GONÇALVES DA SILVA",
    "MATHEUS RODRIGUES GONCALES", "RUBENS FERREIRA DE LIMA JÚNIOR",
    "EDUARDO GAVIRA BONANI", "GUILHERME DE ALMEIDA BRITO RICHARD", "MICHEL CHAPARRO",
    "MARCELA DA CONCEIÇÃO SILVA", "CELSO DE HYPÓLITO", "ANTONIO AFONSO BRAGIÃO",
    "SANDRA MONICA DO NASCIMENTO MOURA", "EDIMILSON CAXEFO", "CLAUDIO EVANGELISTA",
    "EVERALDO MARQUES DA SILVA", "GEOVANI PATROCINIO BARBOSA", "CLEITON VAZ CHAVES",
    "GUSTAVO DO CARMO"
]

nomes_unicos = list(set(nomes))
gestores = list(Gestores.objects.all())

for i, nome in enumerate(nomes_unicos):
    Responsaveis.objects.create(
        nome=nome,
        email=f'{nome.lower().replace(" ", ".").replace("ã", "a").replace("ç", "c")}@empresa.com',
        ni=100000 + i,
        gestor=random.choice(gestores),
        is_superUser=False,
        is_staff=False
    )

print("Responsáveis criados com sucesso!")